name: Go Test

on:
  pull_request:
    paths:
      - "go/**"
  push:
    branches:
      - main
    paths:
      - "go/**"

defaults:
  run:
    working-directory: go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go/go.mod"

      - run: go test -v ./...
