name: Go Test

on: push

defaults:
  run:
    working-directory: go

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go/go.mod"

      - run: go test -v ./...
